---
binary_sensor:
  - platform: template
    sensors:
      front_door_state:
        friendly_name: "Front Door"
        device_class: door
        value_template: "{{ is_state('sensor.aeon_labs_zw120_door_window_sensor_gen5_access_control', '22') }}"
      front_door_tamper_state:
        friendly_name: "Front Door"
        device_class: problem
        value_template: "{{ is_state('sensor.aeon_labs_zw120_door_window_sensor_gen5_burglar', '3') }}"
