---
homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  packages: !include_dir_named packages
  time_zone: Europe/London
  customize: !include customize.yaml
