---
title: Home
views:
  - badges: []
    cards:
      - cards:
          - elements: null
            entities:
              - entity: person.matt_craven
              - entity: person.jenelle
            type: entities
          - content: |
              Placeholder
            elements: null
            type: markdown
        type: horizontal-stack
    icon: 'mdi:home'
    panel: true
    path: default
    title: Default
  - badges: []
    cards:
      - cards:
          - content: |
              Placeholder for **AppleTV**, once tvOS13 is supported.
            elements: null
            type: markdown
          - elements: null
            entity: media_player.sonos_one
            show_header_toggle: false
            title: Speakers
            type: media-control
        type: horizontal-stack
    icon: 'mdi:seat'
    panel: true
    path: living-room
    title: Living Room
  - badges: []
    cards:
      - cards:
          - elements: null
            entity: light.philips_lct015_bede8d03_level_light_color_on_off
            show_header_toggle: false
            title: Master Bedroom Light
            type: light
          - elements: null
            entity: media_player.master_bedroom_speaker
            show_header_toggle: false
            title: Speakers
            type: media-control
        type: horizontal-stack
    icon: 'mdi:bed-king'
    panel: true
    path: master-bedroom
    title: Master Bedroom
  - badges: []
    cards:
      - cards:
          - elements: null
            entities:
              - entity: media_player.sonos_one
              - entity: light.philips_lct015_d8ab5704_level_light_color_on_off
              - entity: switch.85207804600194a4b484_1
              - entity: switch.85207804600194a4b484_2
              - entity: switch.85207804600194a4b484_3
              - entity: switch.85207804600194a4b484_7
              - entity: switch.smart_plug
              - entity: binary_sensor.patio_door_state
              - entity: sensor.aeon_labs_zw112_door_window_sensor_6_battery_level
            show_header_toggle: false
            title: All Living Room Objects
            type: entities
          - elements: null
            entities:
              - entity: media_player.master_bedroom_speaker
              - entity: light.philips_lct015_bede8d03_level_light_color_on_off
            show_header_toggle: false
            title: All Master Bedroom Objects
            type: entities
        type: horizontal-stack
      - entities:
          - sensor.jenelles_parents_feels_like_temperature
          - sensor.jenelles_parents_humidity
          - sensor.jenelles_parents_probability_of_precipitation
          - sensor.jenelles_parents_uv
          - sensor.jenelles_parents_temperature
          - sensor.jenelles_parents_visibility
          - sensor.jenelles_parents_visibility_distance
          - sensor.jenelles_parents_weather
          - sensor.jenelles_parents_wind_direction
          - sensor.jenelles_parents_wind_gust
          - sensor.jenelles_parents_wind_speed
        type: entities
    icon: 'mdi:help-circle'
    panel: false
    path: debug
    title: Debug - Show All
