title: Home
resources:
  - url: /local/cards/vertical-stack-in-card.js?v=0.1.3
    type: js
views:
  - badges: []
    cards:
      - cards:
          - cards:
              - cards:
                  - elements: null
                    type: entities
                    entities:
                      - entity: person.matt_craven
                        name: Matt Craven (iCloud)
                        icon: "mdi:apple-icloud"
                      - entity: device_tracker.life360_matt_craven
                        name: Matt Craven (life360)
                        icon: "mdi:radar"
                      - entity: device_tracker.iphonexs_matt
                        name: Matt's iPhone XS Max
                        icon: "mdi:cellphone-iphone"
                      - entity: device_tracker.mattsapple_watch
                        name: Matt's Apple Watch
                        icon: "mdi:watch"
                    title: Matt's Status
                    show_header_toggle: false
                  - type: entities
                    entities:
                      - entity: person.jenelle
                        name: Jenelle (person)
                        icon: "mdi:account-box"
                      - entity: device_tracker.life360_jenelle
                        name: Jenelle (life360)
                        icon: "mdi:radar"
                    title: Jenelle's Status
                    show_header_toggle: false
                type: horizontal-stack
              - cards:
                  - elements: null
                    type: entities
                    entities:
                      - entity: binary_sensor.front_door_state
                      - entity: binary_sensor.patio_door_state
                      - entity: binary_sensor.spare_sensor_state
                    title: House Security (Door Sensors)
                    show_header_toggle: false
                  - type: entities
                    entities:
                      - entity: sensor.ring_front_door_last_ding
                        icon: "mdi:bell-ring"
                      - entity: sensor.ring_front_door_last_motion
                        icon: "mdi:motion-sensor"
                      - entity: sensor.ring_front_door_battery
                    title: House Security (Ring Doorbell)
                    show_header_toggle: false
                type: horizontal-stack
              - cards:
                  - elements: null
                    type: entities
                    entities:
                      - entity: light.philips_lct015_bede8d03_level_light_color_on_off
                        icon: "mdi:ceiling-light"
                      - entity: light.philips_lct015_d8ab5704_level_light_color_on_off
                        icon: "mdi:ceiling-light"
                      - entity: light.philips_lst002_b5b1f603_level_light_color_on_off
                        name: TV Light Strip
                        icon: "mdi:led-strip-variant"
                    title: House Lights
                    show_header_toggle: false
                  - type: entities
                    entities:
                      - entity: switch.85207804600194a4b484_1
                        icon: "mdi:apple"
                      - entity: switch.85207804600194a4b484_2
                        icon: "mdi:television"
                      - entity: switch.85207804600194a4b484_3
                        icon: "mdi:speaker"
                      - entity: switch.85207804600194a4b484_7
                        icon: "mdi:usb"
                    title: House Plugs
                    show_header_toggle: false
                type: horizontal-stack
            type: "custom:vertical-stack-in-card"
        type: "custom:vertical-stack-in-card"
    type: "custom:vertical-stack-in-card"
    icon: "mdi:home"
    panel: true
    path: default
    title: Default
  - badges: []
    cards:
      - cards:
          - cards:
              - cards:
                  - cards:
                      - elements: null
                        entity: group.all_living_room_lights
                        show_header_toggle: false
                        title: All Living Room Lights
                        type: light
                      - elements: null
                        entity: media_player.sonos_one
                        show_header_toggle: false
                        title: Speakers
                        type: media-control
                  - cards:
                      - elements: null
                        entity: light.philips_lct015_d8ab5704_level_light_color_on_off
                        show_header_toggle: false
                        title: Living Room Light
                        icon: "mdi:ceiling-light"
                        type: light
                      - elements: null
                        entity: light.philips_lst002_b5b1f603_level_light_color_on_off
                        show_header_toggle: false
                        title: TV Light Strip
                        icon: "mdi:led-strip-variant"
                        type: light
                    type: horizontal-stack
                type: "custom:vertical-stack-in-card"
            type: horizontal-stack
        type: "custom:vertical-stack-in-card"
    icon: "mdi:seat"
    panel: true
    path: living-room
    title: Living Room
  - badges: []
    cards:
      - cards:
          - elements: null
            entity: light.philips_lct015_bede8d03_level_light_color_on_off
            show_header_toggle: false
            title: Master Bedroom Light
            icon: "mdi:ceiling-light"
            type: light
          - elements: null
            entity: media_player.master_bedroom_speaker
            show_header_toggle: false
            title: Speakers
            type: media-control
        type: horizontal-stack
    icon: "mdi:bed-king"
    panel: true
    path: master-bedroom
    title: Master Bedroom
  - badges: []
    cards:
      - cards:
          - cards:
              - cards:
                  - cards:
                      - elements: null
                        entities:
                          - entity: sensor.current_version
                          - entity: sensor.latest_version
                        show_header_toggle: false
                        title: Home Assistant Versions
                        type: entities
                      - elements: null
                        entities:
                          - entity: sensor.process_sshd
                          - entity: sensor.process_chronyd
                        show_header_toggle: false
                        title: Home Assistant Processes
                        type: entities
                    type: horizontal-stack
                  - cards:
                      - elements: null
                        entities:
                          - entity: sensor.time_online
                          - entity: sensor.last_boot
                          - entity: sensor.cpu_temperature
                          - entity: sensor.ipv4_address_eth0
                        show_header_toggle: false
                        title: Home Assistant Details
                        type: entities
                      - elements: null
                        entities:
                          - entity: sensor.processor_use
                          - entity: sensor.memory_use_percent
                          - entity: sensor.disk_use_percent
                          - entity: sensor.swap_use_percent
                        show_header_toggle: false
                        title: Home Assistant Usage (%)
                        type: entities
                    type: horizontal-stack
                type: "custom:vertical-stack-in-card"
            type: horizontal-stack
        type: "custom:vertical-stack-in-card"
    icon: "mdi:raspberry-pi"
    panel: true
    path: raspberry-pi
    title: Raspberry Pi Information
  - badges: []
    cards:
      - cards:
          - elements: null
            entities:
              - entity: media_player.sonos_one
              - entity: light.philips_lct015_d8ab5704_level_light_color_on_off
              - entity: switch.85207804600194a4b484_1
              - entity: switch.85207804600194a4b484_2
              - entity: switch.85207804600194a4b484_3
              - entity: switch.85207804600194a4b484_7
              - entity: switch.smart_plug
              - entity: binary_sensor.patio_door_state
              - entity: sensor.aeon_labs_zw112_door_window_sensor_6_battery_level
            show_header_toggle: false
            title: All Living Room Objects
            type: entities
          - elements: null
            entities:
              - entity: media_player.master_bedroom_speaker
              - entity: light.philips_lct015_bede8d03_level_light_color_on_off
            show_header_toggle: false
            title: All Master Bedroom Objects
            type: entities
        type: horizontal-stack
      - entities:
          - sensor.jenelles_parents_feels_like_temperature
          - sensor.jenelles_parents_humidity
          - sensor.jenelles_parents_probability_of_precipitation
          - sensor.jenelles_parents_uv
          - sensor.jenelles_parents_temperature
          - sensor.jenelles_parents_visibility
          - sensor.jenelles_parents_visibility_distance
          - sensor.jenelles_parents_weather
          - sensor.jenelles_parents_wind_direction
          - sensor.jenelles_parents_wind_gust
          - sensor.jenelles_parents_wind_speed
        type: entities
    icon: "mdi:help-circle"
    panel: false
    path: debug
    title: Debug - Show All
