---
title: Default
icon: "mdi:home"
panel: true
path: default
badges: []
cards:
  - cards:
      - cards:
          - cards:
              - elements: null
                type: entities
                entities:
                  - entity: device_tracker.life360_matt_craven
                    name: Matt Craven (life360)
                    icon: "mdi:radar"
                  - entity: device_tracker.iphonexs_matt
                    name: Matt's iPhone XS Max (Mobile App)
                    icon: "mdi:cellphone-iphone"
                  - entity: sensor.battery_level
                    name: Matt's iPhone XS Max Battery State (Mobile App)
                    icon: "mdi:cellphone-iphone"
                title: Matt's Status
                show_header_toggle: false
              - type: entities
                entities:
                  - entity: person.jenelle
                    name: Jenelle (person)
                    icon: "mdi:account-box"
                  - entity: device_tracker.life360_jenelle
                    name: Jenelle (life360)
                    icon: "mdi:radar"
                title: Jenelle's Status
                show_header_toggle: false
            type: horizontal-stack
          - cards:
              - elements: null
                type: entities
                entities:
                  - entity: binary_sensor.front_door_state
                  - entity: binary_sensor.patio_door_state
                  - entity: binary_sensor.spare_sensor_state
                title: House Security (Door Sensors)
                show_header_toggle: false
              - type: entities
                entities:
                  - entity: sensor.front_door_last_ding
                    icon: "mdi:bell-ring"
                  - entity: sensor.front_door_last_motion
                    icon: "mdi:motion-sensor"
                  - entity: sensor.front_door_battery
                title: House Security (Ring Doorbell)
                show_header_toggle: false
            type: horizontal-stack
          - cards:
              - elements: null
                type: slider-entity
                entities:
                  - type: slider-entity
                    entity: light.philips_lct015_bede8d03_level_light_color_on_off
                    icon: "mdi:ceiling-light"
                  - type: slider-entity
                    entity: light.philips_lct015_d8ab5704_level_light_color_on_off
                    icon: "mdi:ceiling-light"
                  - type: slider-entity
                    entity: light.philips_lst002_b5b1f603_level_light_color_on_off
                    name: TV Light Strip
                    icon: "mdi:led-strip-variant"
                title: House Lights
                show_header_toggle: false
              - type: entities
                entities:
                  - entity: switch.85207804600194a4b484_1
                    icon: "mdi:apple"
                  - entity: switch.85207804600194a4b484_2
                    icon: "mdi:television"
                  - entity: switch.85207804600194a4b484_3
                    icon: "mdi:speaker"
                  - entity: switch.85207804600194a4b484_7
                    icon: "mdi:usb"
                title: House Plugs
                show_header_toggle: false
            type: horizontal-stack
        type: "custom:vertical-stack-in-card"
    type: "custom:vertical-stack-in-card"
type: "custom:vertical-stack-in-card"
