---
sensor:
  - platform: metoffice
    api_key: !secret metOffice_apiKey
    name: Home
    monitored_conditions:
      - weather
      - temperature
      - feels_like_temperature
      - wind_speed
      - wind_direction
      - wind_gust
      - visibility
      - visibility_distance
      - uv
      - precipitation
      - humidity

  - platform: metoffice
    api_key: !secret metOffice_apiKey
    name: Jenelles Parents
    latitude: !secret jenellesParents_latitude
    longitude: !secret jenellesParents_longitude
    monitored_conditions:
      - weather
      - temperature
      - feels_like_temperature
      - wind_speed
      - wind_direction
      - wind_gust
      - visibility
      - visibility_distance
      - uv
      - precipitation
      - humidity

