---
automation:
  - alias: Turn Christmas Lights on
    trigger:
      - platform: sun
        event: sunset
    condition: []
    action:
      - service: switch.turn_on
        data_template:
          entity_id: switch.smart_plug

  - alias: Turn Christmas Lights on
    trigger:
      - platform: time
        at: '01:30:00'
    condition: []
    action:
      - service: switch.turn_off
        data_template:
          entity_id: switch.smart_plug
