---
automation:
  - alias: Holiday || Lights on at Night
    trigger:
      - platform: state
        entity_id: sun.sun
        from: "above_horizon"
        to: "below_horizon"
    action:
      - service: light.turn_on
        entity_id:
          - light.philips_lct015_bede8d03_level_light_color_on_off
        data:
          brightness_pct: 50
          rgb_color: [255,0,0]
          transition: 10
      - service: light.turn_on
        entity_id:
          - light.philips_lct015_d8ab5704_level_light_color_on_off
        data:
          brightness_pct: 50
          rgb_color: [255,0,0]
          transition: 10
      - service: switch.turn_on
        entity_id:
          - switch.smart_plug
  - alias: Holiday || Lights Off Midnight
    trigger:
      - platform: time
        at: "00:00"
    action:
      - service: light.turn_off
        entity_id:
          - light.philips_lct015_bede8d03_level_light_color_on_off
      - delay: "00:{{ '{:02}'.format(range(1, 29) | random | int) }}:00"
      - service: switch.turn_off
        entity_id:
          - switch.smart_plug
  - alias: Holiday || Lights Off ~10pm
    trigger:
      - platform: time
        at: "00:00"
    action:
      - service: light.turn_off
        entity_id:
          - light.philips_lct015_d8ab5704_level_light_color_on_off
      - delay: "00:{{ '{:02}'.format(range(1, 29) | random | int) }}:00"
