---
sensor:
  - platform: here_travel_time
    app_key: !secret here_api_key
    name: Morning Commute HERE
    origin_latitude: !secret homeAssistant_latitude
    origin_longitude: !secret homeAssistant_longitude
    destination_latitude: !secret work_latitude
    destination_longitude: !secret work_longitude
    mode: car
    route_mode: fastest
    traffic_mode: true
    unit_system: imperial
    scan_interval: 2678400 # 1 month
